local achievements = {list = {}, popups = {}, popupDuration = 3.5, popupSlideTime = 0.4, gameData = {totalKills = 0, totalScore = 0, powerupsCollected = 0, maxLevel = 1, flawlessRounds = 0, currentRoundDamage = 0, maxRound = 1}}
function achievements.init() achievements.list = {{id = "first_kill", nameKey = "ach_first_kill", descKey = "ach_first_kill_desc", check = function(d) return d.totalKills >= 1 end, unlocked = false},{id = "killer", nameKey = "ach_killer", descKey = "ach_killer_desc", check = function(d) return d.totalKills >= 100 end, unlocked = false},{id = "score_1000", nameKey = "ach_score_1000", descKey = "ach_score_1000_desc", check = function(d) return d.totalScore >= 1000 end, unlocked = false},{id = "score_5000", nameKey = "ach_score_5000", descKey = "ach_score_5000_desc", check = function(d) return d.totalScore >= 5000 end, unlocked = false},{id = "collector", nameKey = "ach_collector", descKey = "ach_collector_desc", check = function(d) return d.powerupsCollected >= 10 end, unlocked = false},{id = "veteran", nameKey = "ach_veteran", descKey = "ach_veteran_desc", check = function(d) return d.maxLevel >= 10 end, unlocked = false},{id = "flawless", nameKey = "ach_flawless", descKey = "ach_flawless_desc", check = function(d) return d.flawlessRounds >= 1 end, unlocked = false},{id = "survivor", nameKey = "ach_survivor", descKey = "ach_survivor_desc", check = function(d) return d.maxRound >= 5 end, unlocked = false}} end
function achievements.resetGameData() achievements.gameData = {totalKills = 0, totalScore = 0, powerupsCollected = 0, maxLevel = 1, flawlessRounds = 0, currentRoundDamage = 0, maxRound = 1}; for _, a in ipairs(achievements.list) do a.unlocked = false end; achievements.popups = {} end
function achievements.update(dt) for i = #achievements.popups, 1, -1 do local p = achievements.popups[i]; p.timer = p.timer - dt; p.slideTimer = p.slideTimer + dt; if p.timer <= 0 then table.remove(achievements.popups, i) end end end
function achievements.check(data) local gd = achievements.gameData; if data.kills then gd.totalKills = gd.totalKills + data.kills end; if data.score then gd.totalScore = math.max(gd.totalScore, data.score) end; if data.powerup then gd.powerupsCollected = gd.powerupsCollected + 1 end; if data.level then gd.maxLevel = math.max(gd.maxLevel, data.level) end; if data.round then gd.maxRound = math.max(gd.maxRound, data.round) end; if data.damage then gd.currentRoundDamage = gd.currentRoundDamage + data.damage end; if data.roundComplete and gd.currentRoundDamage == 0 then gd.flawlessRounds = gd.flawlessRounds + 1 end; if data.roundComplete then gd.currentRoundDamage = 0 end; for _, ach in ipairs(achievements.list) do if not ach.unlocked and ach.check(gd) then ach.unlocked = true; achievements.triggerPopup(ach); return ach end end end
function achievements.triggerPopup(ach) table.insert(achievements.popups, {ach = ach, timer = achievements.popupDuration, slideTimer = 0}) end
function achievements.draw(screenW, screenH, i18n, assets) local cardW = 260; local cardH = 75; local margin = 15; local startX = screenW - cardW - margin; for i, p in ipairs(achievements.popups) do local targetY = margin + (i - 1) * (cardH + 10); local progress = math.min(1, p.slideTimer / achievements.popupSlideTime); local ease = 1 - (1 - progress)^3; local x = startX + (1 - ease) * (cardW + margin * 2); local alpha = 1; if p.timer < 0.5 then alpha = p.timer / 0.5 end; love.graphics.setColor(0.1, 0.12, 0.18, 0.92 * alpha); love.graphics.rectangle("fill", x, targetY, cardW, cardH, 8, 8); love.graphics.setColor(0.3, 0.7, 1, 0.6 * alpha); love.graphics.rectangle("line", x, targetY, cardW, cardH, 8, 8); love.graphics.setColor(1, 0.85, 0.2, 0.8 * alpha); love.graphics.rectangle("fill", x + 4, targetY + 8, 4, cardH - 16, 2, 2); love.graphics.setColor(1, 0.85, 0.2, alpha); assets.setFont(16); love.graphics.print("★", x + 20, targetY + cardH/2 - 10); love.graphics.setColor(1, 1, 1, alpha); assets.setFont(15); love.graphics.print(i18n.t("achievement_unlocked"), x + 50, targetY + 10); assets.setFont(14); love.graphics.setColor(0.8, 0.9, 1, alpha); love.graphics.print(i18n.t(p.ach.nameKey), x + 50, targetY + 32); love.graphics.setColor(0.6, 0.7, 0.8, alpha); love.graphics.print(i18n.t(p.ach.descKey), x + 50, targetY + 50) end end
function achievements.getList() return achievements.list end
function achievements.isUnlocked(id) for _, a in ipairs(achievements.list) do if a.id == id then return a.unlocked end end return false end
return achievements
