return {
    name = "English",
    title = "Star Guardian",
    subtitle = "SPACE SHOOTER",
    score = "Score", highscore = "High Score", level = "Level", hp = "HP",
    start = "Start Game", ship_select = "Select Ship", settings = "Settings",
    back = "Back", select = "Select", continue = "Continue",
    move_desc = "A/D or Arrow Keys to Move", shoot_desc = "Space to Shoot", pause_desc = "P to Pause",
    mobile_move = "D-pad to Move", mobile_shoot = "Fire Button to Shoot", mobile_pause = "Pause Button to Pause",
    paused = "PAUSED", continue_hint = "Press P to Continue", continue_tap = "Tap to Continue",
    game_over = "GAME OVER", final_score = "Final Score", new_record = "NEW RECORD!",
    restart_hint = "Press ENTER to Restart", restart_tap = "Tap to Restart",
    start_hint = "Press ENTER to Start", tap_hint = "Tap to Start",
    lang_label = "Language", master_vol = "Master Volume", sfx_vol = "SFX Volume", music_vol = "Music Volume",
    language_menu = "Language",
    round = "Round", round_complete = "Round Complete", next_round = "Next Round",
    ship_striker = "Striker", ship_fortress = "Fortress", ship_phantom = "Phantom", ship_destroyer = "Destroyer",
    stats_speed = "Speed", stats_firepower = "Firepower", stats_hp = "HP", stats_skill = "Skill",
    skill_none = "Balanced - No special skill", skill_double = "Double Shot - Fires two bullets",
    skill_penetrate = "Piercing - Bullets pass through enemies", skill_heavy = "Heavy - High damage & HP",
    achievement_unlocked = "Achievement Unlocked!",
    ach_first_kill = "First Blood", ach_first_kill_desc = "Destroy your first enemy",
    ach_killer = "Killer", ach_killer_desc = "Destroy 100 enemies",
    ach_score_1000 = "Score Hunter", ach_score_1000_desc = "Reach 1000 points",
    ach_score_5000 = "Score Master", ach_score_5000_desc = "Reach 5000 points",
    ach_collector = "Collector", ach_collector_desc = "Pick up 10 power-ups",
    ach_veteran = "Veteran", ach_veteran_desc = "Reach level 10",
    ach_flawless = "Flawless", ach_flawless_desc = "Complete a round without taking damage",
    ach_survivor = "Survivor", ach_survivor_desc = "Reach Round 5",
}
