return {
    name = "日本語",
    title = "スターガーディアン", subtitle = "宇宙シューティング",
    score = "スコア", highscore = "最高スコア", level = "レベル", hp = "HP",
    start = "ゲーム開始", ship_select = "機体選択", settings = "設定",
    back = "戻る", select = "選択", continue = "続ける",
    move_desc = "A/Dまたは矢印キーで移動", shoot_desc = "スペースで発射", pause_desc = "Pで一時停止",
    mobile_move = "方向キーで移動", mobile_shoot = "発射ボタン", mobile_pause = "停止ボタン",
    paused = "一時停止", continue_hint = "Pで再開", continue_tap = "タップで再開",
    game_over = "ゲームオーバー", final_score = "最終スコア", new_record = "新記録!",
    restart_hint = "ENTERで再開", restart_tap = "タップで再開",
    start_hint = "ENTERで開始", tap_hint = "タップで開始",
    lang_label = "言語", master_vol = "マスター音量", sfx_vol = "効果音", music_vol = "音楽音量",
    language_menu = "言語",
    round = "ラウンド", round_complete = "ラウンドクリア", next_round = "次のラウンド",
    ship_striker = "ストライカー", ship_fortress = "フォートレス", ship_phantom = "ファントム", ship_destroyer = "デストロイヤー",
    stats_speed = "速度", stats_firepower = "火力", stats_hp = "HP", stats_skill = "スキル",
    skill_none = "バランス型", skill_double = "ダブルショット", skill_penetrate = "貫通弾", skill_heavy = "重装型",
    achievement_unlocked = "実績解除!",
    ach_first_kill = "ファーストブラッド", ach_first_kill_desc = "最初の敵を撃破",
    ach_killer = "キラー", ach_killer_desc = "敵を100体撃破",
    ach_score_1000 = "スコアハンター", ach_score_1000_desc = "1000点達成",
    ach_score_5000 = "スコアマスター", ach_score_5000_desc = "5000点達成",
    ach_collector = "コレクター", ach_collector_desc = "パワーアップを10個取得",
    ach_veteran = "ベテラン", ach_veteran_desc = "レベル10到達",
    ach_flawless = "完璧", ach_flawless_desc = "ダメージなしでラウンドクリア",
    ach_survivor = "サバイバー", ach_survivor_desc = "ラウンド5到達",
}
