return {
    name = "中文",
    title = "星际守护者", subtitle = "太空射击",
    score = "分数", highscore = "最高分", level = "等级", hp = "生命",
    start = "开始游戏", ship_select = "选择战机", settings = "设置",
    back = "返回", select = "选择", continue = "继续",
    move_desc = "A/D 或方向键移动", shoot_desc = "空格键射击", pause_desc = "P键暂停",
    mobile_move = "方向键移动", mobile_shoot = "射击键开火", mobile_pause = "暂停键暂停",
    paused = "已暂停", continue_hint = "按P继续", continue_tap = "点击继续",
    game_over = "游戏结束", final_score = "最终分数", new_record = "新纪录!",
    restart_hint = "按回车重新开始", restart_tap = "点击重新开始",
    start_hint = "按回车开始", tap_hint = "点击开始",
    lang_label = "语言", master_vol = "主音量", sfx_vol = "音效音量", music_vol = "音乐音量",
    language_menu = "语言",
    round = "第", round_complete = "关卡完成", next_round = "下一关",
    resume = "继续游戏", exit_to_menu = "返回主菜单",
    exit_title = "返回主菜单？", exit_msg = "当前进度不会保存。",
    exit_yes = "是", exit_no = "否",
    round1_name = "侦察机入侵", round1_desc = "轻型侦察编队，热身一下",
    round2_name = "战斗机中队", round2_desc = "摇摆机动的敌机，注意走位",
    round3_name = "重型装甲", round3_desc = "装甲厚重，需要持续火力",
    round4_name = "极速突袭", round4_desc = "高速敌机来袭，考验反应",
    round5_name = "全面战争", round5_desc = "倾巢而出，火力全开",
    round6_name = "无尽模式", round6_desc = "无穷无尽的敌人，坚持到底",
    ship_striker = "突击者", ship_fortress = "重装机甲", ship_phantom = "幻影", ship_destroyer = "毁灭者",
    stats_speed = "速度", stats_firepower = "火力", stats_hp = "生命", stats_skill = "技能",
    skill_none = "均衡型 - 无特殊技能", skill_double = "双发 - 同时发射两发子弹",
    skill_penetrate = "穿透 - 子弹可穿透敌人", skill_heavy = "重装 - 高伤害高生命",
    achievement_unlocked = "成就解锁!",
    ach_first_kill = "初次击杀", ach_first_kill_desc = "击败第一个敌人",
    ach_killer = "杀手", ach_killer_desc = "击败100个敌人",
    ach_score_1000 = "分数猎手", ach_score_1000_desc = "达到1000分",
    ach_score_5000 = "分数大师", ach_score_5000_desc = "达到5000分",
    ach_collector = "收藏家", ach_collector_desc = "拾取10个道具",
    ach_veteran = "老兵", ach_veteran_desc = "达到10级",
    ach_flawless = "完美", ach_flawless_desc = "无伤通过一个关卡",
    ach_survivor = "幸存者", ach_survivor_desc = "到达第5关",
}
